export const IPC_CHANNELS = {
  projectCreate: 'project:create',
  projectOpen: 'project:open',
  projectOpenRecent: 'project:open-recent',
  projectSave: 'project:save',
  projectSaveAs: 'project:save-as',
  projectDuplicate: 'project:duplicate',
  projectRecentList: 'project:recent-list',
  projectRecentRemove: 'project:recent-remove',
  projectClearCache: 'project:clear-cache',
  projectExportPortable: 'project:export-portable',
  projectImportPortable: 'project:import-portable',
  projectRelocateMissing: 'project:relocate-missing',
  importSelect: 'import:select',
  importFolder: 'import:folder',
  importDropped: 'import:dropped',
  importCommit: 'import:commit',
  previewPlan: 'preview:plan',
  previewThumbnail: 'preview:thumbnail',
  previewRefresh: 'preview:refresh',
  exportPreflight: 'export:preflight',
  exportStart: 'export:start',
  exportCancel: 'export:cancel',
  exportProgress: 'export:progress',
  exportFinished: 'export:finished',
  printGetPayload: 'print:get-payload',
  printReady: 'print:ready',
  systemOpenPath: 'system:open-path',
  systemRevealPath: 'system:reveal-path',
  systemOpenExternal: 'system:open-external',
  appBeforeClose: 'app:before-close',
  appCloseResponse: 'app:close-response',
  appSetDirty: 'app:set-dirty',
  appCommand: 'app:command',
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
