import type {
  LayoutSheet,
  LayoutTemplateId,
  Project,
  TargetOrientation,
} from '../schemas/project-schema.js'
import { createLayoutSection, createLayoutSheet } from './layout-tree.js'

export type CollageSourcePage = {
  sourcePageId: string
  materialId: string
  outlineNodeId: string
  sourceKind: 'pdf' | 'image'
  aspectRatio?: number
}

export type CollageSuggestion = {
  templateId: LayoutTemplateId
  orientation: TargetOrientation
  sheets: LayoutSheet[]
  sourcePageCount: number
  composedPageCount: number
  reason: string
}

const pickTemplate = (count: number, averageAspectRatio: number): LayoutTemplateId => {
  if (count <= 2) return 'two-up'
  if (averageAspectRatio < 0.55 && count <= 4) return 'vertical-strips'
  if (count <= 4) return 'four-up'
  return 'certificate-2x3'
}

const templateCapacity = (templateId: LayoutTemplateId): number => {
  switch (templateId) {
    case 'two-up':
    case 'front-back':
    case 'original-with-detail':
      return 2
    case 'four-up':
    case 'certificate-2x2':
    case 'primary-with-attachments':
    case 'multi-material-sections':
    case 'vertical-strips':
      return 4
    case 'certificate-2x3':
    case 'contact-sheet':
      return 6
  }
}

const groupByMaterial = (pages: readonly CollageSourcePage[]): Map<string, CollageSourcePage[]> => {
  const grouped = new Map<string, CollageSourcePage[]>()
  pages.forEach((page) => {
    const existing = grouped.get(page.materialId) ?? []
    existing.push(page)
    grouped.set(page.materialId, existing)
  })
  return grouped
}

export const suggestCollage = (input: {
  pages: readonly CollageSourcePage[]
  project: Pick<Project, 'collageSettings'>
  existingSheetCount: number
  allowCrossMaterial: boolean
  crossDirectoryConfirmed: boolean
}): CollageSuggestion => {
  if (input.pages.length < 2) {
    throw new Error('至少选择两个来源页面才能生成拼版建议。')
  }
  const materialIds = new Set(input.pages.map((page) => page.materialId))
  const outlineNodeIds = new Set(input.pages.map((page) => page.outlineNodeId))
  if (!input.allowCrossMaterial && materialIds.size > 1) {
    throw new Error('自动建议默认不跨成果；请显式启用跨成果拼版。')
  }
  if (outlineNodeIds.size > 1 && !input.crossDirectoryConfirmed) {
    throw new Error('跨目录拼版必须先确认成果归属和目录顺序。')
  }
  const averageAspectRatio =
    input.pages.reduce((total, page) => total + (page.aspectRatio ?? 0.707), 0) / input.pages.length
  const templateId =
    materialIds.size > 1
      ? 'multi-material-sections'
      : pickTemplate(input.pages.length, averageAspectRatio)
  const capacity = Math.min(
    templateCapacity(templateId),
    input.project.collageSettings.maxAutoSlotsPerSheet,
  )
  const orientation: TargetOrientation =
    averageAspectRatio > 1.1 || materialIds.size > 1 ? 'landscape' : 'portrait'
  const sheets: LayoutSheet[] = []

  if (materialIds.size > 1) {
    const maximumPerSheet = input.project.collageSettings.maxAutoSlotsPerSheet
    let index = 0
    while (index < input.pages.length) {
      const sheetPages: CollageSourcePage[] = []
      const materialCounts = new Map<string, number>()
      while (index < input.pages.length && sheetPages.length < maximumPerSheet) {
        const candidate = input.pages[index]
        if (!candidate) break
        const currentMaterialCount = materialCounts.get(candidate.materialId) ?? 0
        // 现有自动模板单个成果区段最多安全容纳 6 个槽；不得调用模板后静默截断。
        if (currentMaterialCount >= 6) break
        sheetPages.push(candidate)
        materialCounts.set(candidate.materialId, currentMaterialCount + 1)
        index += 1
      }
      const firstSheetPage = sheetPages[0]
      if (!firstSheetPage) {
        throw new Error('无法在自动拼版上限内放置所选页面。')
      }
      const grouped = groupByMaterial(sheetPages)
      const sections = [...grouped.entries()].map(([materialId, pages]) =>
        createLayoutSection(
          materialId,
          pages.map((page) => page.sourcePageId),
          pages.length <= 2 ? 'two-up' : pages.length <= 4 ? 'four-up' : 'certificate-2x3',
        ),
      )
      sheets.push(
        createLayoutSheet({
          anchorSourcePageId: firstSheetPage.sourcePageId,
          sections,
          order: input.existingSheetCount + sheets.length,
          orientation,
          templateId,
          project: input.project,
          crossDirectoryConfirmed: outlineNodeIds.size <= 1 || input.crossDirectoryConfirmed,
          autoGenerated: true,
        }),
      )
    }
  } else {
    for (let index = 0; index < input.pages.length; index += capacity) {
      const pageGroup = input.pages.slice(index, index + capacity)
      const first = pageGroup[0]
      if (!first) continue
      const section = createLayoutSection(
        first.materialId,
        pageGroup.map((page) => page.sourcePageId),
        templateId,
      )
      sheets.push(
        createLayoutSheet({
          anchorSourcePageId: first.sourcePageId,
          sections: [section],
          order: input.existingSheetCount + sheets.length,
          orientation,
          templateId,
          project: input.project,
          autoGenerated: true,
        }),
      )
    }
  }

  return {
    templateId,
    orientation,
    sheets,
    sourcePageCount: input.pages.length,
    composedPageCount: sheets.length,
    reason:
      materialIds.size > 1
        ? '多个成果采用全宽上下区段，避免专家混淆归属。'
        : `根据 ${input.pages.length} 个页面及宽高比选择 ${templateId} 模板。`,
  }
}
