import { z } from 'zod'
import {
  IssueSeveritySchema,
  LayoutAlignmentSchema,
  LayoutFitSchema,
  LayoutNodeSchema,
  NormalizedCropRectSchema,
  RotationSchema,
  TargetOrientationSchema,
  ValidationStatusSchema,
} from './project-schema.js'

export const PageTypeSchema = z.enum([
  'cover',
  'blank',
  'toc',
  'divider',
  'materialTitle',
  'pdfContent',
  'imageContent',
  'compositeContent',
])

export const LogicalPageNumberSchema = z.object({
  value: z.number().int().positive(),
  label: z.string().min(1),
})

export const ValidationIssueSchema = z.object({
  code: z.string().min(1),
  severity: IssueSeveritySchema,
  message: z.string().min(1),
  outlineNodeId: z.uuid().nullable(),
  materialId: z.uuid().nullable(),
})

export const InlineHeadingSchema = z.object({
  level: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  title: z.string().min(1),
  sequenceLabel: z.string().min(1),
  text: z.string().min(1),
})

export const PlannedContentItemSchema = z.object({
  slotId: z.uuid(),
  materialId: z.uuid(),
  outlineNodeId: z.uuid(),
  sourceId: z.uuid(),
  sourceFile: z.string().min(1),
  sourcePageIndex: z.number().int().nonnegative(),
  sourcePageId: z.string().min(1),
  sourceKind: z.enum(['pdf', 'image']),
  sourceRotation: RotationSchema,
  slotRotation: RotationSchema,
  cropRect: NormalizedCropRectSchema,
  fit: LayoutFitSchema,
  alignment: LayoutAlignmentSchema,
  detailOf: z.string().min(1).nullable(),
  clarityRiskAcknowledged: z.boolean(),
})

export const PlannedLayoutSectionSchema = z.object({
  id: z.uuid(),
  materialId: z.uuid(),
  outlineNodeId: z.uuid(),
  materialTitle: z.string().min(1),
  sequenceLabel: z.string().min(1),
  heightWeight: z.number().int().min(1).max(10000),
  showContinuationTitle: z.boolean(),
  isContinuation: z.boolean(),
  layout: LayoutNodeSchema,
})

export const CompositePagePlanSchema = z.object({
  layoutSheetId: z.uuid(),
  layoutDigest: z.string().min(1),
  margins: z.object({
    top: z.number().min(0).max(144),
    right: z.number().min(0).max(144),
    bottom: z.number().min(0).max(144),
    left: z.number().min(0).max(144),
  }),
  sectionGapPoints: z.number().min(0).max(72),
  slotGapPoints: z.number().min(0).max(36),
  locked: z.boolean(),
  autoGenerated: z.boolean(),
  sections: z.array(PlannedLayoutSectionSchema).min(1).max(12),
  contentItems: z.array(PlannedContentItemSchema).min(1).max(24),
})

export const PlannedPageSchema = z.object({
  id: z.string().min(1),
  physicalIndex: z.number().int().nonnegative(),
  pageType: PageTypeSchema,
  outlineNodeId: z.uuid().nullable(),
  materialId: z.uuid().nullable(),
  outlineNodeIds: z.array(z.uuid()),
  materialIds: z.array(z.uuid()),
  sourceId: z.uuid().nullable(),
  sourceFile: z.string().nullable(),
  sourcePageIndex: z.number().int().nonnegative().nullable(),
  sourcePageId: z.string().nullable(),
  displayTitle: z.string(),
  sequenceLabel: z.string().nullable(),
  inlineHeadings: z.array(InlineHeadingSchema),
  logicalPageNumber: LogicalPageNumberSchema.nullable(),
  showPageNumber: z.boolean(),
  printedPageLabel: z.string().nullable(),
  rotation: RotationSchema,
  targetOrientation: TargetOrientationSchema,
  validationStatus: ValidationStatusSchema,
  composite: CompositePagePlanSchema.nullable(),
})

export const TocEntrySchema = z.object({
  id: z.string().min(1),
  kind: z.enum(['level1', 'level2', 'material']),
  level: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  title: z.string().min(1),
  sequenceLabel: z.string().min(1),
  displayText: z.string().min(1),
  outlineNodeId: z.uuid().nullable(),
  materialId: z.uuid().nullable(),
  logicalPageNumber: z.number().int().positive(),
})

export const PlannedSectionSchema = z.object({
  id: z.string().min(1),
  outlineNodeId: z.uuid().nullable(),
  materialId: z.uuid().nullable(),
  startPhysicalIndex: z.number().int().nonnegative(),
  endPhysicalIndex: z.number().int().nonnegative(),
  startLogicalPage: z.number().int().positive().nullable(),
  endLogicalPage: z.number().int().positive().nullable(),
})

export const PagePlanSchema = z.object({
  planFingerprint: z.string().min(1),
  projectId: z.uuid(),
  revision: z.number().int().nonnegative(),
  totalPageCount: z.number().int().nonnegative(),
  logicalPageCount: z.number().int().nonnegative(),
  tocPageCount: z.number().int().nonnegative(),
  pages: z.array(PlannedPageSchema),
  sections: z.array(PlannedSectionSchema),
  outlineStartPages: z.record(z.string(), z.number().int().positive()),
  materialStartPages: z.record(z.string(), z.number().int().positive()),
  materialEndPages: z.record(z.string(), z.number().int().positive()),
  outlineSequenceLabels: z.record(z.string(), z.string().min(1)),
  materialSequenceLabels: z.record(z.string(), z.string().min(1)),
  outputOutlineNodeIds: z.array(z.uuid()),
  outputMaterialIds: z.array(z.uuid()),
  tocEntries: z.array(TocEntrySchema),
  errors: z.array(ValidationIssueSchema),
  warnings: z.array(ValidationIssueSchema),
})

export type PageType = z.infer<typeof PageTypeSchema>
export type LogicalPageNumber = z.infer<typeof LogicalPageNumberSchema>
export type ValidationIssue = z.infer<typeof ValidationIssueSchema>
export type InlineHeading = z.infer<typeof InlineHeadingSchema>
export type PlannedContentItem = z.infer<typeof PlannedContentItemSchema>
export type PlannedLayoutSection = z.infer<typeof PlannedLayoutSectionSchema>
export type CompositePagePlan = z.infer<typeof CompositePagePlanSchema>
export type PlannedPage = z.infer<typeof PlannedPageSchema>
export type TocEntry = z.infer<typeof TocEntrySchema>
export type PlannedSection = z.infer<typeof PlannedSectionSchema>
export type PagePlan = z.infer<typeof PagePlanSchema>
