import { z } from 'zod'
import {
  DEFAULT_PAGE_MARGINS_POINTS,
  DEFAULT_PAGE_NUMBER_BOTTOM_OFFSET_POINTS,
} from '../constants/document.js'

export const AssetStorageModeSchema = z.enum(['copy', 'reference'])
export const SourceTypeSchema = z.enum(['pdf', 'image', 'imageCollection', 'office', 'mixed'])
export const MaterialSourceTypeSchema = z.enum(['pdf', 'image', 'office'])
export const OfficeFormatSchema = z.enum(['docx', 'pptx', 'xlsx'])
export const ConversionSnapshotStatusSchema = z.enum(['ready', 'stale', 'error'])
export const ValidationStatusSchema = z.enum([
  'valid',
  'warning',
  'error',
  'missing',
  'encrypted',
  'unsupported',
])
export const IssueSeveritySchema = z.enum(['error', 'warning', 'info'])
export const RotationSchema = z.union([z.literal(0), z.literal(90), z.literal(180), z.literal(270)])
export const TargetOrientationSchema = z.enum(['portrait', 'landscape'])
export const ImageQualitySchema = z.enum(['screen', 'standard', 'high'])
export const PageNumberPositionSchema = z.enum(['bottomCenter', 'bottomRight'])
export const PageNumberFormatSchema = z.enum(['number', 'dash', 'chinese', 'fraction'])
export const ContentHeadingModeSchema = z.enum(['none', 'firstPage'])
export const MaterialStartPolicySchema = z.enum(['newSheet', 'allowSharedSheet'])
export const LayoutFitSchema = z.enum(['contain', 'cover', 'fitWidth', 'fitHeight'])
export const LayoutAlignmentSchema = z.enum([
  'topLeft',
  'topCenter',
  'topRight',
  'centerLeft',
  'center',
  'centerRight',
  'bottomLeft',
  'bottomCenter',
  'bottomRight',
])
export const LayoutSplitDirectionSchema = z.enum(['row', 'column'])
export const LayoutTemplateIdSchema = z.enum([
  'two-up',
  'four-up',
  'certificate-2x2',
  'certificate-2x3',
  'front-back',
  'primary-with-attachments',
  'multi-material-sections',
  'contact-sheet',
  'vertical-strips',
  'original-with-detail',
])

export const NormalizedCropRectSchema = z
  .object({
    x: z.number().int().min(0).max(9999),
    y: z.number().int().min(0).max(9999),
    width: z.number().int().min(1).max(10000),
    height: z.number().int().min(1).max(10000),
  })
  .superRefine((rect, context) => {
    if (rect.x + rect.width > 10000 || rect.y + rect.height > 10000) {
      context.addIssue({
        code: 'custom',
        message: '裁切框不能超出来源页面边界。',
      })
    }
  })

export type LayoutSlot = {
  kind: 'slot'
  id: string
  sourcePageId: string | null
  cropRect: z.infer<typeof NormalizedCropRectSchema>
  fit: z.infer<typeof LayoutFitSchema>
  alignment: z.infer<typeof LayoutAlignmentSchema>
  rotation: z.infer<typeof RotationSchema>
  detailOf: string | null
  clarityRiskAcknowledged: boolean
}

export type LayoutSplit = {
  kind: 'split'
  id: string
  direction: z.infer<typeof LayoutSplitDirectionSchema>
  weights: number[]
  children: LayoutNode[]
}

export type LayoutNode = LayoutSlot | LayoutSplit

export const LayoutSlotSchema: z.ZodType<LayoutSlot> = z.object({
  kind: z.literal('slot'),
  id: z.uuid(),
  sourcePageId: z.string().min(1).nullable(),
  cropRect: NormalizedCropRectSchema,
  fit: LayoutFitSchema,
  alignment: LayoutAlignmentSchema,
  rotation: RotationSchema,
  detailOf: z.string().min(1).nullable(),
  clarityRiskAcknowledged: z.boolean(),
})

export const LayoutNodeSchema: z.ZodType<LayoutNode> = z.lazy(() =>
  z.union([
    LayoutSlotSchema,
    z
      .object({
        kind: z.literal('split'),
        id: z.uuid(),
        direction: LayoutSplitDirectionSchema,
        weights: z.array(z.number().int().min(1).max(9999)).min(2).max(24),
        children: z.array(LayoutNodeSchema).min(2).max(24),
      })
      .superRefine((split, context) => {
        if (split.weights.length !== split.children.length) {
          context.addIssue({
            code: 'custom',
            path: ['weights'],
            message: '分割比例数量必须与子区域数量一致。',
          })
        }
        if (split.weights.reduce((total, weight) => total + weight, 0) !== 10000) {
          context.addIssue({
            code: 'custom',
            path: ['weights'],
            message: '分割比例之和必须为 10000。',
          })
        }
      }),
  ]),
)

export const LayoutSectionSchema = z.object({
  id: z.uuid(),
  materialId: z.uuid(),
  heightWeight: z.number().int().min(1).max(10000),
  showContinuationTitle: z.boolean(),
  layout: LayoutNodeSchema,
})

export const LayoutSheetSchema = z
  .object({
    id: z.uuid(),
    order: z.number().int().nonnegative(),
    anchorSourcePageId: z.string().min(1),
    orientation: TargetOrientationSchema,
    margins: z.object({
      top: z.number().min(0).max(144),
      right: z.number().min(0).max(144),
      bottom: z.number().min(0).max(144),
      left: z.number().min(0).max(144),
    }),
    sectionGapPoints: z.number().min(0).max(72),
    slotGapPoints: z.number().min(0).max(36),
    locked: z.boolean(),
    autoGenerated: z.boolean(),
    templateId: LayoutTemplateIdSchema.nullable(),
    crossDirectoryConfirmed: z.boolean(),
    sections: z.array(LayoutSectionSchema).min(1).max(12),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
  })
  .superRefine((sheet, context) => {
    if (sheet.sections.reduce((total, section) => total + section.heightWeight, 0) !== 10000) {
      context.addIssue({
        code: 'custom',
        path: ['sections'],
        message: '拼版页成果区段高度比例之和必须为 10000。',
      })
    }
    const materialIds = new Set<string>()
    sheet.sections.forEach((section, index) => {
      if (materialIds.has(section.materialId)) {
        context.addIssue({
          code: 'custom',
          path: ['sections', index, 'materialId'],
          message: '同一成果在一张拼版页中只能有一个全宽区段。',
        })
      }
      materialIds.add(section.materialId)
    })
  })

export const CollageSettingsSchema = z
  .object({
    enabled: z.boolean(),
    defaultOrientation: TargetOrientationSchema,
    defaultMargins: z.object({
      top: z.number().min(0).max(144),
      right: z.number().min(0).max(144),
      bottom: z.number().min(0).max(144),
      left: z.number().min(0).max(144),
    }),
    defaultSectionGapPoints: z.number().min(0).max(72),
    defaultSlotGapPoints: z.number().min(0).max(36),
    autoCropEnabled: z.boolean(),
    autoCropSafetyMillimeters: z.number().min(0).max(20),
    rasterPreferredDpi: z.number().int().min(72).max(600),
    rasterMinimumAutoDpi: z.number().int().min(72).max(600),
    pdfWarningScale: z.number().min(0.1).max(1),
    pdfMinimumAutoScale: z.number().min(0.1).max(1),
    maxAutoSlotsPerSheet: z.number().int().min(1).max(12),
    maxManualSlotsPerSheet: z.number().int().min(1).max(24),
  })
  .superRefine((settings, context) => {
    if (settings.rasterPreferredDpi < settings.rasterMinimumAutoDpi) {
      context.addIssue({
        code: 'custom',
        path: ['rasterPreferredDpi'],
        message: '图片推荐 DPI 不能低于自动拼版最低 DPI。',
      })
    }
    if (settings.pdfWarningScale < settings.pdfMinimumAutoScale) {
      context.addIssue({
        code: 'custom',
        path: ['pdfWarningScale'],
        message: 'PDF 警告缩放比例不能低于自动拼版最低缩放比例。',
      })
    }
    if (settings.maxManualSlotsPerSheet < settings.maxAutoSlotsPerSheet) {
      context.addIssue({
        code: 'custom',
        path: ['maxManualSlotsPerSheet'],
        message: '手动拼版槽位上限不能低于自动拼版槽位上限。',
      })
    }
  })

export const ValidationMessageSchema = z.object({
  code: z.string().min(1).max(100),
  severity: IssueSeveritySchema,
  message: z.string().min(1).max(1000),
  suggestion: z.string().max(1000).optional(),
})

export const OfficeConversionSchema = z.object({
  adapterId: z.literal('libreoffice'),
  engineVersion: z.string().min(1).max(100),
  officeFormat: OfficeFormatSchema,
  pdfStoredPath: z.string().min(1).max(4096),
  sourceFileHash: z.string().regex(/^[a-f0-9]{64}$/i),
  fileHash: z.string().regex(/^[a-f0-9]{64}$/i),
  fileSize: z.number().int().positive(),
  pageCount: z.number().int().positive(),
  convertedAt: z.iso.datetime(),
  snapshotStatus: ConversionSnapshotStatusSchema,
  warnings: z.array(z.string().min(1).max(1000)).max(100),
})

export const MaterialSourceSchema = z.object({
  id: z.uuid(),
  sourceType: MaterialSourceTypeSchema,
  sourcePath: z.string().min(1),
  storedPath: z.string().min(1).nullable(),
  originalFileName: z.string().min(1).max(255),
  fileHash: z.string().regex(/^[a-f0-9]{64}$/i),
  fileSize: z.number().int().nonnegative(),
  modifiedTime: z.number().int().nonnegative(),
  mimeType: z.string().min(1).max(200),
  pageCount: z.number().int().positive(),
  selectedPageRanges: z.string().min(1).max(4096),
  width: z.number().positive().optional(),
  height: z.number().positive().optional(),
  exifOrientation: z.number().int().min(1).max(8).optional(),
  conversion: OfficeConversionSchema.optional(),
})

export const MaterialSchema = z
  .object({
    id: z.uuid(),
    outlineNodeId: z.uuid(),
    title: z.string().min(1).max(300),
    category: z.string().max(100),
    sourceType: SourceTypeSchema,
    sourcePath: z.string().min(1),
    storedPath: z.string().min(1).nullable(),
    originalFileName: z.string().min(1).max(255),
    fileHash: z.string().regex(/^[a-f0-9]{64}$/i),
    fileSize: z.number().int().nonnegative(),
    modifiedTime: z.number().int().nonnegative(),
    pageCount: z.number().int().positive(),
    selectedPageRanges: z.string().min(1).max(4096),
    pageOrder: z.array(z.string().min(1)),
    rotationByPage: z.record(z.string(), RotationSchema),
    removedPages: z.array(z.string().min(1)),
    enabled: z.boolean(),
    startPolicy: MaterialStartPolicySchema,
    insertTitlePage: z.boolean(),
    notes: z.string().max(5000),
    validationStatus: ValidationStatusSchema,
    validationMessages: z.array(ValidationMessageSchema),
    order: z.number().int().nonnegative(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    sourceItems: z.array(MaterialSourceSchema).min(1),
  })
  .superRefine((material, context) => {
    if (material.sourceType === 'imageCollection' && material.sourceItems.length < 2) {
      context.addIssue({
        code: 'custom',
        path: ['sourceItems'],
        message: '图片集合至少需要两张图片。',
      })
    }
    if (
      material.sourceType === 'imageCollection' &&
      material.sourceItems.some((source) => source.sourceType !== 'image')
    ) {
      context.addIssue({
        code: 'custom',
        path: ['sourceItems'],
        message: '图片集合只能包含图片来源。',
      })
    }
    if (
      ['pdf', 'image', 'office'].includes(material.sourceType) &&
      material.sourceItems.length !== 1
    ) {
      context.addIssue({
        code: 'custom',
        path: ['sourceItems'],
        message: '单文件材料必须且只能包含一个来源文件；多文件成果请使用混合材料。',
      })
    }
    if (material.sourceType === 'mixed' && material.sourceItems.length < 2) {
      context.addIssue({
        code: 'custom',
        path: ['sourceItems'],
        message: '混合材料至少需要两个来源文件。',
      })
    }
    if (
      material.sourceItems.length === 1 &&
      ['pdf', 'image', 'office'].includes(material.sourceType) &&
      material.sourceItems[0]?.sourceType !== material.sourceType
    ) {
      context.addIssue({
        code: 'custom',
        path: ['sourceItems', 0, 'sourceType'],
        message: '单文件材料类型必须与来源文件类型一致。',
      })
    }
    material.sourceItems.forEach((source, index) => {
      if (source.sourceType === 'office' && !source.conversion) {
        context.addIssue({
          code: 'custom',
          path: ['sourceItems', index, 'conversion'],
          message: 'Office 来源必须包含可用的 PDF 转换快照。',
        })
      }
      if (source.sourceType !== 'office' && source.conversion !== undefined) {
        context.addIssue({
          code: 'custom',
          path: ['sourceItems', index, 'conversion'],
          message: '非 Office 来源不能包含 Office 转换快照。',
        })
      }
      if (source.sourceType === 'image' && source.pageCount !== 1) {
        context.addIssue({
          code: 'custom',
          path: ['sourceItems', index, 'pageCount'],
          message: '图片来源页数必须为 1。',
        })
      }
    })
  })

export type Material = z.infer<typeof MaterialSchema>

export type OutlineNode = {
  id: string
  parentId: string | null
  level: 1 | 2
  title: string
  order: number
  enabled: boolean
  insertDividerPage: boolean
  children: OutlineNode[]
  materials: Material[]
}

export const OutlineNodeSchema: z.ZodType<OutlineNode> = z.lazy(() =>
  z.object({
    id: z.uuid(),
    parentId: z.uuid().nullable(),
    level: z.union([z.literal(1), z.literal(2)]),
    title: z.string().min(1).max(200),
    order: z.number().int().nonnegative(),
    enabled: z.boolean(),
    insertDividerPage: z.boolean(),
    children: z.array(OutlineNodeSchema),
    materials: z.array(MaterialSchema),
  }),
)

export const CoverSettingsSchema = z.object({
  enabled: z.boolean(),
  title: z.string().min(1).max(300),
  ownerName: z.string().max(100),
  organization: z.string().max(200),
  purpose: z.string().max(500),
  compiledDate: z.iso.date(),
  insertBlankBackPage: z.boolean().default(true),
  showPageNumber: z.boolean(),
  countInLogicalNumber: z.boolean(),
})

export const TocSettingsSchema = z.object({
  enabled: z.boolean(),
  title: z.string().min(1).max(100),
  showPageNumber: z.boolean(),
  countInLogicalNumber: z.boolean(),
})

export const PageNumberSettingsSchema = z.object({
  enabled: z.boolean(),
  bodyStartNumber: z.number().int().positive(),
  position: PageNumberPositionSchema,
  format: PageNumberFormatSchema,
  fontSize: z.number().min(8).max(18),
  bottomOffsetPoints: z.number().min(8).max(30),
  showOnDivider: z.boolean(),
  showOnMaterialTitle: z.boolean(),
})

export const PdfMetadataSchema = z.object({
  title: z.string().max(300),
  author: z.string().max(200),
  subject: z.string().max(500),
  creator: z.string().max(200),
  producer: z.string().max(200),
})

export const ExportSettingsSchema = z.object({
  outputFileName: z.string().min(1).max(255),
  includeCover: z.boolean(),
  includeToc: z.boolean(),
  includeDividerPages: z.boolean(),
  includeMaterialTitlePages: z.boolean(),
  contentHeadingMode: ContentHeadingModeSchema.default('firstPage'),
  addPageNumbers: z.boolean(),
  targetOrientation: TargetOrientationSchema,
  margins: z.object({
    top: z.number().min(0).max(144),
    right: z.number().min(0).max(144),
    bottom: z.number().min(0).max(144),
    left: z.number().min(0).max(144),
  }),
  imageQuality: ImageQualitySchema,
  metadata: PdfMetadataSchema,
  overwriteExisting: z.boolean(),
  openAfterExport: z.boolean(),
  revealAfterExport: z.boolean(),
})

export const ProjectSchema = z
  .object({
    id: z.uuid(),
    schemaVersion: z.literal(3),
    title: z.string().min(1).max(300),
    ownerName: z.string().max(100),
    organization: z.string().max(200),
    purpose: z.string().max(500),
    compiledDate: z.iso.date(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    projectDirectory: z.literal('.'),
    assetStorageMode: AssetStorageModeSchema,
    coverSettings: CoverSettingsSchema,
    tocSettings: TocSettingsSchema,
    pageNumberSettings: PageNumberSettingsSchema,
    exportSettings: ExportSettingsSchema,
    collageSettings: CollageSettingsSchema,
    layoutSheets: z.array(LayoutSheetSchema),
    outlineNodes: z.array(OutlineNodeSchema),
  })
  .superRefine((project, context) => {
    const ids = new Set<string>()
    const visit = (
      node: OutlineNode,
      expectedParent: string | null,
      expectedLevel: 1 | 2,
    ): void => {
      if (ids.has(node.id)) {
        context.addIssue({
          code: 'custom',
          path: ['outlineNodes'],
          message: `目录节点 ID 重复：${node.id}`,
        })
      }
      ids.add(node.id)
      if (node.parentId !== expectedParent || node.level !== expectedLevel) {
        context.addIssue({
          code: 'custom',
          path: ['outlineNodes'],
          message: `目录“${node.title}”的层级或父节点配置无效。`,
        })
      }
      if (node.level === 1 && node.materials.length > 0) {
        context.addIssue({
          code: 'custom',
          path: ['outlineNodes'],
          message: `一级目录“${node.title}”不能直接包含材料。`,
        })
      }
      if (node.level === 2 && node.children.length > 0) {
        context.addIssue({
          code: 'custom',
          path: ['outlineNodes'],
          message: `二级目录“${node.title}”不能继续包含子目录。`,
        })
      }
      node.materials.forEach((material) => {
        if (material.outlineNodeId !== node.id) {
          context.addIssue({
            code: 'custom',
            path: ['outlineNodes'],
            message: `材料“${material.title}”引用了错误的目录节点。`,
          })
        }
      })
      node.children.forEach((child) => {
        visit(child, node.id, 2)
      })
    }
    project.outlineNodes.forEach((node) => {
      visit(node, null, 1)
    })
  })

export type Project = z.infer<typeof ProjectSchema>
export type MaterialSource = z.infer<typeof MaterialSourceSchema>
export type MaterialSourceType = z.infer<typeof MaterialSourceTypeSchema>
export type OfficeConversion = z.infer<typeof OfficeConversionSchema>
export type OfficeFormat = z.infer<typeof OfficeFormatSchema>
export type ValidationMessage = z.infer<typeof ValidationMessageSchema>
export type Rotation = z.infer<typeof RotationSchema>
export type ValidationStatus = z.infer<typeof ValidationStatusSchema>
export type TargetOrientation = z.infer<typeof TargetOrientationSchema>
export type ImageQuality = z.infer<typeof ImageQualitySchema>
export type ContentHeadingMode = z.infer<typeof ContentHeadingModeSchema>
export type MaterialStartPolicy = z.infer<typeof MaterialStartPolicySchema>
export type LayoutFit = z.infer<typeof LayoutFitSchema>
export type LayoutAlignment = z.infer<typeof LayoutAlignmentSchema>
export type LayoutSplitDirection = z.infer<typeof LayoutSplitDirectionSchema>
export type LayoutTemplateId = z.infer<typeof LayoutTemplateIdSchema>
export type NormalizedCropRect = z.infer<typeof NormalizedCropRectSchema>
export type LayoutSection = z.infer<typeof LayoutSectionSchema>
export type LayoutSheet = z.infer<typeof LayoutSheetSchema>
export type CollageSettings = z.infer<typeof CollageSettingsSchema>

export const createDefaultCollageSettings = (): CollageSettings => ({
  enabled: true,
  defaultOrientation: 'portrait',
  defaultMargins: { ...DEFAULT_PAGE_MARGINS_POINTS },
  defaultSectionGapPoints: 10,
  defaultSlotGapPoints: 6,
  autoCropEnabled: true,
  autoCropSafetyMillimeters: 3,
  rasterPreferredDpi: 180,
  rasterMinimumAutoDpi: 150,
  pdfWarningScale: 0.6,
  pdfMinimumAutoScale: 0.5,
  maxAutoSlotsPerSheet: 12,
  maxManualSlotsPerSheet: 24,
})

export const createDefaultProject = (
  input: {
    title: string
    ownerName?: string
    organization?: string
    purpose?: string
    compiledDate?: string
    outlineNodes?: OutlineNode[]
  },
  now = new Date(),
): Project => {
  const iso = now.toISOString()
  const date = input.compiledDate ?? iso.slice(0, 10)
  const ownerName = input.ownerName ?? ''
  const organization = input.organization ?? ''
  const purpose = input.purpose ?? ''

  return ProjectSchema.parse({
    id: crypto.randomUUID(),
    schemaVersion: 3,
    title: input.title,
    ownerName,
    organization,
    purpose,
    compiledDate: date,
    createdAt: iso,
    updatedAt: iso,
    projectDirectory: '.',
    assetStorageMode: 'copy',
    coverSettings: {
      enabled: true,
      title: input.title,
      ownerName,
      organization,
      purpose,
      compiledDate: date,
      insertBlankBackPage: true,
      showPageNumber: false,
      countInLogicalNumber: false,
    },
    tocSettings: {
      enabled: true,
      title: '支撑材料目录',
      showPageNumber: false,
      countInLogicalNumber: false,
    },
    pageNumberSettings: {
      enabled: true,
      bodyStartNumber: 1,
      position: 'bottomCenter',
      format: 'dash',
      fontSize: 12,
      bottomOffsetPoints: DEFAULT_PAGE_NUMBER_BOTTOM_OFFSET_POINTS,
      showOnDivider: true,
      showOnMaterialTitle: true,
    },
    exportSettings: {
      outputFileName: `${input.title}.pdf`,
      includeCover: true,
      includeToc: true,
      includeDividerPages: true,
      includeMaterialTitlePages: true,
      contentHeadingMode: 'firstPage',
      addPageNumbers: true,
      targetOrientation: 'portrait',
      margins: DEFAULT_PAGE_MARGINS_POINTS,
      imageQuality: 'standard',
      metadata: {
        title: input.title,
        author: ownerName,
        subject: purpose,
        creator: '个人支撑材料编排器',
        producer: 'SupportPackBuilder',
      },
      overwriteExisting: false,
      openAfterExport: false,
      revealAfterExport: true,
    },
    collageSettings: createDefaultCollageSettings(),
    layoutSheets: [],
    outlineNodes: input.outlineNodes ?? [],
  })
}
